// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable 0612, 0618, 1591, 3021
namespace namaichi.utility
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Timestamp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Timestamp()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"seconds")]
        public long Seconds { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"nanos")]
        public int Nanos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Duration : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Duration()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"seconds")]
        public long Seconds { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"nanos")]
        public int Nanos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ModeratorUserInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ModeratorUserInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"user_id")]
        public long UserId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"nickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname
        {
            get { return __pbn__Nickname ?? ""; }
            set { __pbn__Nickname = value; }
        }
        public bool ShouldSerializeNickname()
        {
            return __pbn__Nickname != null;
        }
        public void ResetNickname()
        {
            __pbn__Nickname = null;
        }
        private string __pbn__Nickname;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string iconUrl
        {
            get { return __pbn__iconUrl ?? ""; }
            set { __pbn__iconUrl = value; }
        }
        public bool ShouldSerializeiconUrl()
        {
            return __pbn__iconUrl != null;
        }
        public void ReseticonUrl()
        {
            __pbn__iconUrl = null;
        }
        private string __pbn__iconUrl;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ModeratorUpdated : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ModeratorUpdated()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"operation")]
        public ModeratorOperation Operation { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"operator")]
        public ModeratorUserInfo Operator { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Timestamp updatedAt { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ModeratorOperation
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ADD")]
            Add = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"DELETE")]
            Delete = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SSNGUpdated : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SSNGUpdated()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"operation")]
        public SSNGOperation Operation { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ssng_id")]
        public long SsngId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"operator")]
        public ModeratorUserInfo Operator { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"type")]
        public SSNGType Type
        {
            get { return __pbn__Type.GetValueOrDefault(); }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType()
        {
            return __pbn__Type != null;
        }
        public void ResetType()
        {
            __pbn__Type = null;
        }
        private SSNGType? __pbn__Type;

        [global::ProtoBuf.ProtoMember(5, Name = @"source")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Source
        {
            get { return __pbn__Source ?? ""; }
            set { __pbn__Source = value; }
        }
        public bool ShouldSerializeSource()
        {
            return __pbn__Source != null;
        }
        public void ResetSource()
        {
            __pbn__Source = null;
        }
        private string __pbn__Source;

        [global::ProtoBuf.ProtoMember(6)]
        public Timestamp updatedAt { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum SSNGOperation
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ADD")]
            Add = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"DELETE")]
            Delete = 1,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum SSNGType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"USER")]
            User = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"WORD")]
            Word = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"COMMAND")]
            Command = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ModerationAnnouncement : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ModerationAnnouncement()
        {
            guidelineItems = new global::System.Collections.Generic.List<GuidelineItem>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message
        {
            get { return __pbn__Message ?? ""; }
            set { __pbn__Message = value; }
        }
        public bool ShouldSerializeMessage()
        {
            return __pbn__Message != null;
        }
        public void ResetMessage()
        {
            __pbn__Message = null;
        }
        private string __pbn__Message;

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public global::System.Collections.Generic.List<GuidelineItem> guidelineItems { get; private set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Timestamp updatedAt { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GuidelineItem
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
            Unknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SEXUAL")]
            Sexual = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"SPAM")]
            Spam = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SLANDER")]
            Slander = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"PERSONAL_INFORMATION")]
            PersonalInformation = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Chat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Chat()
        {
            Content = "";
            Name = "";
            HashedUserId = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"vpos")]
        public int Vpos { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public AccountStatus account_status { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"raw_user_id")]
        public long RawUserId
        {
            get { return __pbn__source.Is(5) ? __pbn__source.Int64 : default(long); }
            set { __pbn__source = new global::ProtoBuf.DiscriminatedUnion64Object(5, value); }
        }
        public bool ShouldSerializeRawUserId()
        {
            return __pbn__source.Is(5);
        }
        public void ResetRawUserId()
        {
            global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__source, 5);
        }

        private global::ProtoBuf.DiscriminatedUnion64Object __pbn__source;

        [global::ProtoBuf.ProtoMember(6, Name = @"hashed_user_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string HashedUserId
        {
            get { return __pbn__source.Is(6) ? ((string)__pbn__source.Object) : ""; }
            set { __pbn__source = new global::ProtoBuf.DiscriminatedUnion64Object(6, value); }
        }
        public bool ShouldSerializeHashedUserId()
        {
            return __pbn__source.Is(6);
        }
        public void ResetHashedUserId()
        {
            global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__source, 6);
        }

        [global::ProtoBuf.ProtoMember(7)]
        public Modifier modifier { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"no")]
        public int No { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Modifier : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public Modifier()
            {
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1, Name = @"position")]
            public Pos Position { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public Size size { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"named_color")]
            public ColorName NamedColor
            {
                get { return __pbn__color.Is(3) ? ((ColorName)__pbn__color.Int32) : default(ColorName); }
                set { __pbn__color = new global::ProtoBuf.DiscriminatedUnion32Object(3, (int)value); }
            }
            public bool ShouldSerializeNamedColor()
            {
                return __pbn__color.Is(3);
            }
            public void ResetNamedColor()
            {
                global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__color, 3);
            }

            private global::ProtoBuf.DiscriminatedUnion32Object __pbn__color;

            [global::ProtoBuf.ProtoMember(4)]
            public FullColor full_color
            {
                get { return __pbn__color.Is(4) ? ((FullColor)__pbn__color.Object) : default(FullColor); }
                set { __pbn__color = new global::ProtoBuf.DiscriminatedUnion32Object(4, value); }
            }
            public bool ShouldSerializefull_color()
            {
                return __pbn__color.Is(4);
            }
            public void Resetfull_color()
            {
                global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__color, 4);
            }

            [global::ProtoBuf.ProtoMember(5)]
            public Font font { get; set; }

            [global::ProtoBuf.ProtoMember(6)]
            public Opacity opacity { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class FullColor : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                {
                    return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
                }
                public FullColor()
                {
                    OnConstructor();
                }

                partial void OnConstructor();

                [global::ProtoBuf.ProtoMember(1, Name = @"r")]
                public int R { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"g")]
                public int G { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"b")]
                public int B { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public enum Pos
            {
                [global::ProtoBuf.ProtoEnum(Name = @"naka")]
                Naka = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"shita")]
                Shita = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"ue")]
                Ue = 2,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum Size
            {
                [global::ProtoBuf.ProtoEnum(Name = @"medium")]
                Medium = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"small")]
                Small = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"big")]
                Big = 2,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum ColorName
            {
                [global::ProtoBuf.ProtoEnum(Name = @"white")]
                White = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"red")]
                Red = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"pink")]
                Pink = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"orange")]
                Orange = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"yellow")]
                Yellow = 4,
                [global::ProtoBuf.ProtoEnum(Name = @"green")]
                Green = 5,
                [global::ProtoBuf.ProtoEnum(Name = @"cyan")]
                Cyan = 6,
                [global::ProtoBuf.ProtoEnum(Name = @"blue")]
                Blue = 7,
                [global::ProtoBuf.ProtoEnum(Name = @"purple")]
                Purple = 8,
                [global::ProtoBuf.ProtoEnum(Name = @"black")]
                Black = 9,
                [global::ProtoBuf.ProtoEnum(Name = @"white2")]
                White2 = 10,
                [global::ProtoBuf.ProtoEnum(Name = @"red2")]
                Red2 = 11,
                [global::ProtoBuf.ProtoEnum(Name = @"pink2")]
                Pink2 = 12,
                [global::ProtoBuf.ProtoEnum(Name = @"orange2")]
                Orange2 = 13,
                [global::ProtoBuf.ProtoEnum(Name = @"yellow2")]
                Yellow2 = 14,
                [global::ProtoBuf.ProtoEnum(Name = @"green2")]
                Green2 = 15,
                [global::ProtoBuf.ProtoEnum(Name = @"cyan2")]
                Cyan2 = 16,
                [global::ProtoBuf.ProtoEnum(Name = @"blue2")]
                Blue2 = 17,
                [global::ProtoBuf.ProtoEnum(Name = @"purple2")]
                Purple2 = 18,
                [global::ProtoBuf.ProtoEnum(Name = @"black2")]
                Black2 = 19,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum Font
            {
                [global::ProtoBuf.ProtoEnum(Name = @"defont")]
                Defont = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"mincho")]
                Mincho = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"gothic")]
                Gothic = 2,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum Opacity
            {
                Normal = 0,
                Translucent = 1,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum AccountStatus
        {
            Standard = 0,
            Premium = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OperatorComment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public OperatorComment()
        {
            Content = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName()
        {
            return __pbn__Name != null;
        }
        public void ResetName()
        {
            __pbn__Name = null;
        }
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(3, Name = @"modifier")]
        public Chat.Modifier Modifier { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"link")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Link
        {
            get { return __pbn__Link ?? ""; }
            set { __pbn__Link = value; }
        }
        public bool ShouldSerializeLink()
        {
            return __pbn__Link != null;
        }
        public void ResetLink()
        {
            __pbn__Link = null;
        }
        private string __pbn__Link;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Jump : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Jump()
        {
            Content = "";
            Message = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"wait")]
        public Duration Wait { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Redirect : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Redirect()
        {
            Uri = "";
            Message = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uri { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"wait")]
        public Duration Wait { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimpleNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SimpleNotification()
        {
            Ichiba = "";
            Quote = "";
            Emotion = "";
            Cruise = "";
            ProgramExtended = "";
            RankingIn = "";
            RankingUpdated = "";
            Visited = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"ichiba")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ichiba
        {
            get { return __pbn__message.Is(1) ? ((string)__pbn__message.Object) : ""; }
            set { __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
        }
        public bool ShouldSerializeIchiba()
        {
            return __pbn__message.Is(1);
        }
        public void ResetIchiba()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 1);
        }

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__message;

        [global::ProtoBuf.ProtoMember(2, Name = @"quote")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Quote
        {
            get { return __pbn__message.Is(2) ? ((string)__pbn__message.Object) : ""; }
            set { __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializeQuote()
        {
            return __pbn__message.Is(2);
        }
        public void ResetQuote()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 2);
        }

        [global::ProtoBuf.ProtoMember(3, Name = @"emotion")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Emotion
        {
            get { return __pbn__message.Is(3) ? ((string)__pbn__message.Object) : ""; }
            set { __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializeEmotion()
        {
            return __pbn__message.Is(3);
        }
        public void ResetEmotion()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 3);
        }

        [global::ProtoBuf.ProtoMember(4, Name = @"cruise")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Cruise
        {
            get { return __pbn__message.Is(4) ? ((string)__pbn__message.Object) : ""; }
            set { __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeCruise()
        {
            return __pbn__message.Is(4);
        }
        public void ResetCruise()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 4);
        }

        [global::ProtoBuf.ProtoMember(5, Name = @"program_extended")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ProgramExtended
        {
            get { return __pbn__message.Is(5) ? ((string)__pbn__message.Object) : ""; }
            set { __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializeProgramExtended()
        {
            return __pbn__message.Is(5);
        }
        public void ResetProgramExtended()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 5);
        }

        [global::ProtoBuf.ProtoMember(6, Name = @"ranking_in")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RankingIn
        {
            get { return __pbn__message.Is(6) ? ((string)__pbn__message.Object) : ""; }
            set { __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(6, value); }
        }
        public bool ShouldSerializeRankingIn()
        {
            return __pbn__message.Is(6);
        }
        public void ResetRankingIn()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 6);
        }

        [global::ProtoBuf.ProtoMember(8, Name = @"ranking_updated")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RankingUpdated
        {
            get { return __pbn__message.Is(8) ? ((string)__pbn__message.Object) : ""; }
            set { __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(8, value); }
        }
        public bool ShouldSerializeRankingUpdated()
        {
            return __pbn__message.Is(8);
        }
        public void ResetRankingUpdated()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 8);
        }

        [global::ProtoBuf.ProtoMember(7, Name = @"visited")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Visited
        {
            get { return __pbn__message.Is(7) ? ((string)__pbn__message.Object) : ""; }
            set { __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(7, value); }
        }
        public bool ShouldSerializeVisited()
        {
            return __pbn__message.Is(7);
        }
        public void ResetVisited()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 7);
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Gift : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Gift()
        {
            ItemId = "";
            AdvertiserName = "";
            Message = "";
            ItemName = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"item_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ItemId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"advertiser_user_id")]
        public long AdvertiserUserId
        {
            get { return __pbn__AdvertiserUserId.GetValueOrDefault(); }
            set { __pbn__AdvertiserUserId = value; }
        }
        public bool ShouldSerializeAdvertiserUserId()
        {
            return __pbn__AdvertiserUserId != null;
        }
        public void ResetAdvertiserUserId()
        {
            __pbn__AdvertiserUserId = null;
        }
        private long? __pbn__AdvertiserUserId;

        [global::ProtoBuf.ProtoMember(3, Name = @"advertiser_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AdvertiserName { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"point")]
        public long Point { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"item_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ItemName { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"contribution_rank")]
        public int ContributionRank
        {
            get { return __pbn__ContributionRank.GetValueOrDefault(); }
            set { __pbn__ContributionRank = value; }
        }
        public bool ShouldSerializeContributionRank()
        {
            return __pbn__ContributionRank != null;
        }
        public void ResetContributionRank()
        {
            __pbn__ContributionRank = null;
        }
        private int? __pbn__ContributionRank;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Nicoad : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Nicoad()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public V0 v0
        {
            get { return __pbn__versions.Is(1) ? ((V0)__pbn__versions.Object) : default(V0); }
            set { __pbn__versions = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
        }
        public bool ShouldSerializev0()
        {
            return __pbn__versions.Is(1);
        }
        public void Resetv0()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__versions, 1);
        }

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__versions;

        [global::ProtoBuf.ProtoMember(2)]
        public V1 v1
        {
            get { return __pbn__versions.Is(2) ? ((V1)__pbn__versions.Object) : default(V1); }
            set { __pbn__versions = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializev1()
        {
            return __pbn__versions.Is(2);
        }
        public void Resetv1()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__versions, 2);
        }

        [global::ProtoBuf.ProtoContract()]
        public partial class V0 : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public V0()
            {
                Rankings = new global::System.Collections.Generic.List<Ranking>();
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1)]
            public Latest latest { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"ranking")]
            public global::System.Collections.Generic.List<Ranking> Rankings { get; private set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"total_point")]
            public int TotalPoint { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class Latest : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                {
                    return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
                }
                public Latest()
                {
                    Advertiser = "";
                    OnConstructor();
                }

                partial void OnConstructor();

                [global::ProtoBuf.ProtoMember(1, Name = @"advertiser")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Advertiser { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"point")]
                public int Point { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"message")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Message
                {
                    get { return __pbn__Message ?? ""; }
                    set { __pbn__Message = value; }
                }
                public bool ShouldSerializeMessage()
                {
                    return __pbn__Message != null;
                }
                public void ResetMessage()
                {
                    __pbn__Message = null;
                }
                private string __pbn__Message;

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class Ranking : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                {
                    return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
                }
                public Ranking()
                {
                    Advertiser = "";
                    OnConstructor();
                }

                partial void OnConstructor();

                [global::ProtoBuf.ProtoMember(1, Name = @"advertiser")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Advertiser { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"rank")]
                public int Rank { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"message")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Message
                {
                    get { return __pbn__Message ?? ""; }
                    set { __pbn__Message = value; }
                }
                public bool ShouldSerializeMessage()
                {
                    return __pbn__Message != null;
                }
                public void ResetMessage()
                {
                    __pbn__Message = null;
                }
                private string __pbn__Message;

                [global::ProtoBuf.ProtoMember(4, Name = @"user_rank")]
                public int UserRank
                {
                    get { return __pbn__UserRank.GetValueOrDefault(); }
                    set { __pbn__UserRank = value; }
                }
                public bool ShouldSerializeUserRank()
                {
                    return __pbn__UserRank != null;
                }
                public void ResetUserRank()
                {
                    __pbn__UserRank = null;
                }
                private int? __pbn__UserRank;

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class V1 : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public V1()
            {
                Message = "";
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1, Name = @"total_ad_point")]
            public int TotalAdPoint { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"message")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Message { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CommentLock : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public CommentLock()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public Status status { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Status
        {
            Unrestricted = 0,
            Locked = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CommentMode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public CommentMode()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public Layout layout { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Layout
        {
            Normal = 0,
            SplitTop = 1,
            Background = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public GameUpdate()
        {
            OnConstructor();
        }

        partial void OnConstructor();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrialPanel : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public TrialPanel()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public Panel panel { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"unqualified_user")]
        public Mode UnqualifiedUser { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Panel
        {
            Hidden = 0,
            Display = 1,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum Mode
        {
            Allowed = 0,
            Restricted = 1,
            Forbidden = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProgramStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ProgramStatus()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public State state { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum State
        {
            Unknown = 0,
            Ended = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TagUpdated : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public TagUpdated()
        {
            Tags = new global::System.Collections.Generic.List<Tag>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"tags")]
        public global::System.Collections.Generic.List<Tag> Tags { get; private set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"owner_locked")]
        public bool OwnerLocked { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Tag : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public Tag()
            {
                Text = "";
                NicopediaUri = "";
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1, Name = @"text")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Text { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"locked")]
            public bool Locked { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"reserved")]
            public bool Reserved { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"nicopedia_uri")]
            [global::System.ComponentModel.DefaultValue("")]
            public string NicopediaUri { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Statistics : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Statistics()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"viewers")]
        public long Viewers
        {
            get { return __pbn__Viewers.GetValueOrDefault(); }
            set { __pbn__Viewers = value; }
        }
        public bool ShouldSerializeViewers()
        {
            return __pbn__Viewers != null;
        }
        public void ResetViewers()
        {
            __pbn__Viewers = null;
        }
        private long? __pbn__Viewers;

        [global::ProtoBuf.ProtoMember(2, Name = @"comments")]
        public long Comments
        {
            get { return __pbn__Comments.GetValueOrDefault(); }
            set { __pbn__Comments = value; }
        }
        public bool ShouldSerializeComments()
        {
            return __pbn__Comments != null;
        }
        public void ResetComments()
        {
            __pbn__Comments = null;
        }
        private long? __pbn__Comments;

        [global::ProtoBuf.ProtoMember(3, Name = @"ad_points")]
        public long AdPoints
        {
            get { return __pbn__AdPoints.GetValueOrDefault(); }
            set { __pbn__AdPoints = value; }
        }
        public bool ShouldSerializeAdPoints()
        {
            return __pbn__AdPoints != null;
        }
        public void ResetAdPoints()
        {
            __pbn__AdPoints = null;
        }
        private long? __pbn__AdPoints;

        [global::ProtoBuf.ProtoMember(4, Name = @"gift_points")]
        public long GiftPoints
        {
            get { return __pbn__GiftPoints.GetValueOrDefault(); }
            set { __pbn__GiftPoints = value; }
        }
        public bool ShouldSerializeGiftPoints()
        {
            return __pbn__GiftPoints != null;
        }
        public void ResetGiftPoints()
        {
            __pbn__GiftPoints = null;
        }
        private long? __pbn__GiftPoints;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Marquee : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Marquee()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public Display display { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Display : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public Display()
            {
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1, Name = @"operator_comment")]
            public OperatorComment OperatorComment { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"duration")]
            public Duration Duration { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Enquete : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Enquete()
        {
            Question = "";
            Choices = new global::System.Collections.Generic.List<Choice>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"question")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Question { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"choices")]
        public global::System.Collections.Generic.List<Choice> Choices { get; private set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Status status { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Choice : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public Choice()
            {
                Description = "";
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1, Name = @"description")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Description { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"per_mille")]
            public int PerMille
            {
                get { return __pbn__PerMille.GetValueOrDefault(); }
                set { __pbn__PerMille = value; }
            }
            public bool ShouldSerializePerMille()
            {
                return __pbn__PerMille != null;
            }
            public void ResetPerMille()
            {
                __pbn__PerMille = null;
            }
            private int? __pbn__PerMille;

        }

        [global::ProtoBuf.ProtoContract()]
        public enum Status
        {
            Closed = 0,
            Poll = 1,
            Result = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoveOrder : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MoveOrder()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"jump")]
        public Jump Jump
        {
            get { return __pbn__to.Is(1) ? ((Jump)__pbn__to.Object) : default(Jump); }
            set { __pbn__to = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
        }
        public bool ShouldSerializeJump()
        {
            return __pbn__to.Is(1);
        }
        public void ResetJump()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__to, 1);
        }

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__to;

        [global::ProtoBuf.ProtoMember(2, Name = @"redirect")]
        public Redirect Redirect
        {
            get { return __pbn__to.Is(2) ? ((Redirect)__pbn__to.Object) : default(Redirect); }
            set { __pbn__to = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializeRedirect()
        {
            return __pbn__to.Is(2);
        }
        public void ResetRedirect()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__to, 2);
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NicoliveOrigin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public NicoliveOrigin()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public Chat chat { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Chat : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public Chat()
            {
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1, Name = @"live_id")]
            public long LiveId { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NicoliveState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public NicoliveState()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"statistics")]
        public Statistics Statistics { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"enquete")]
        public Enquete Enquete { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"move_order")]
        public MoveOrder MoveOrder { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"marquee")]
        public Marquee Marquee { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"comment_lock")]
        public CommentLock CommentLock { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"comment_mode")]
        public CommentMode CommentMode { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"trial_panel")]
        public TrialPanel TrialPanel { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"program_status")]
        public ProgramStatus ProgramStatus { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"moderation_announcement")]
        public ModerationAnnouncement ModerationAnnouncement { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NicoliveMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public NicoliveMessage()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"chat")]
        public Chat Chat
        {
            get { return __pbn__data.Is(1) ? ((Chat)__pbn__data.Object) : default(Chat); }
            set { __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
        }
        public bool ShouldSerializeChat()
        {
            return __pbn__data.Is(1);
        }
        public void ResetChat()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 1);
        }

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__data;

        [global::ProtoBuf.ProtoMember(7, Name = @"simple_notification")]
        public SimpleNotification SimpleNotification
        {
            get { return __pbn__data.Is(7) ? ((SimpleNotification)__pbn__data.Object) : default(SimpleNotification); }
            set { __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(7, value); }
        }
        public bool ShouldSerializeSimpleNotification()
        {
            return __pbn__data.Is(7);
        }
        public void ResetSimpleNotification()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 7);
        }

        [global::ProtoBuf.ProtoMember(8, Name = @"gift")]
        public Gift Gift
        {
            get { return __pbn__data.Is(8) ? ((Gift)__pbn__data.Object) : default(Gift); }
            set { __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(8, value); }
        }
        public bool ShouldSerializeGift()
        {
            return __pbn__data.Is(8);
        }
        public void ResetGift()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 8);
        }

        [global::ProtoBuf.ProtoMember(9, Name = @"nicoad")]
        public Nicoad Nicoad
        {
            get { return __pbn__data.Is(9) ? ((Nicoad)__pbn__data.Object) : default(Nicoad); }
            set { __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(9, value); }
        }
        public bool ShouldSerializeNicoad()
        {
            return __pbn__data.Is(9);
        }
        public void ResetNicoad()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 9);
        }

        [global::ProtoBuf.ProtoMember(13, Name = @"game_update")]
        public GameUpdate GameUpdate
        {
            get { return __pbn__data.Is(13) ? ((GameUpdate)__pbn__data.Object) : default(GameUpdate); }
            set { __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(13, value); }
        }
        public bool ShouldSerializeGameUpdate()
        {
            return __pbn__data.Is(13);
        }
        public void ResetGameUpdate()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 13);
        }

        [global::ProtoBuf.ProtoMember(17, Name = @"tag_updated")]
        public TagUpdated TagUpdated
        {
            get { return __pbn__data.Is(17) ? ((TagUpdated)__pbn__data.Object) : default(TagUpdated); }
            set { __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(17, value); }
        }
        public bool ShouldSerializeTagUpdated()
        {
            return __pbn__data.Is(17);
        }
        public void ResetTagUpdated()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 17);
        }

        [global::ProtoBuf.ProtoMember(18, Name = @"moderator_updated")]
        public ModeratorUpdated ModeratorUpdated
        {
            get { return __pbn__data.Is(18) ? ((ModeratorUpdated)__pbn__data.Object) : default(ModeratorUpdated); }
            set { __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(18, value); }
        }
        public bool ShouldSerializeModeratorUpdated()
        {
            return __pbn__data.Is(18);
        }
        public void ResetModeratorUpdated()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 18);
        }

        [global::ProtoBuf.ProtoMember(19, Name = @"ssng_updated")]
        public SSNGUpdated SsngUpdated
        {
            get { return __pbn__data.Is(19) ? ((SSNGUpdated)__pbn__data.Object) : default(SSNGUpdated); }
            set { __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(19, value); }
        }
        public bool ShouldSerializeSsngUpdated()
        {
            return __pbn__data.Is(19);
        }
        public void ResetSsngUpdated()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 19);
        }

        [global::ProtoBuf.ProtoMember(20, Name = @"overflowed_chat")]
        public Chat OverflowedChat
        {
            get { return __pbn__data.Is(20) ? ((Chat)__pbn__data.Object) : default(Chat); }
            set { __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(20, value); }
        }
        public bool ShouldSerializeOverflowedChat()
        {
            return __pbn__data.Is(20);
        }
        public void ResetOverflowedChat()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 20);
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChunkedMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ChunkedMessage()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public Meta meta { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"message")]
        public NicoliveMessage Message
        {
            get { return __pbn__payload.Is(2) ? ((NicoliveMessage)__pbn__payload.Object) : default(NicoliveMessage); }
            set { __pbn__payload = new global::ProtoBuf.DiscriminatedUnion32Object(2, value); }
        }
        public bool ShouldSerializeMessage()
        {
            return __pbn__payload.Is(2);
        }
        public void ResetMessage()
        {
            global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__payload, 2);
        }

        private global::ProtoBuf.DiscriminatedUnion32Object __pbn__payload;

        [global::ProtoBuf.ProtoMember(4, Name = @"state")]
        public NicoliveState State
        {
            get { return __pbn__payload.Is(4) ? ((NicoliveState)__pbn__payload.Object) : default(NicoliveState); }
            set { __pbn__payload = new global::ProtoBuf.DiscriminatedUnion32Object(4, value); }
        }
        public bool ShouldSerializeState()
        {
            return __pbn__payload.Is(4);
        }
        public void ResetState()
        {
            global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__payload, 4);
        }

        [global::ProtoBuf.ProtoMember(5)]
        public Signal signal
        {
            get { return __pbn__payload.Is(5) ? ((Signal)__pbn__payload.Int32) : default(Signal); }
            set { __pbn__payload = new global::ProtoBuf.DiscriminatedUnion32Object(5, (int)value); }
        }
        public bool ShouldSerializesignal()
        {
            return __pbn__payload.Is(5);
        }
        public void Resetsignal()
        {
            global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__payload, 5);
        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Meta : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public Meta()
            {
                Id = "";
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1, Name = @"id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Id { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"at")]
            public Timestamp At { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"origin")]
            public NicoliveOrigin Origin { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum Signal
        {
            Flushed = 0,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PackedSegment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PackedSegment()
        {
            Messages = new global::System.Collections.Generic.List<ChunkedMessage>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"messages")]
        public global::System.Collections.Generic.List<ChunkedMessage> Messages { get; private set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Next next { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"snapshot")]
        public StateSnapshot Snapshot { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Next : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public Next()
            {
                Uri = "";
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1, Name = @"uri")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Uri { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class StateSnapshot : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public StateSnapshot()
            {
                Uri = "";
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1, Name = @"uri")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Uri { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChunkedEntry : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ChunkedEntry()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(2, Name = @"backward")]
        public BackwardSegment Backward
        {
            get { return __pbn__entry.Is(2) ? ((BackwardSegment)__pbn__entry.Object) : default(BackwardSegment); }
            set { __pbn__entry = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializeBackward()
        {
            return __pbn__entry.Is(2);
        }
        public void ResetBackward()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__entry, 2);
        }

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__entry;

        [global::ProtoBuf.ProtoMember(3, Name = @"previous")]
        public MessageSegment Previous
        {
            get { return __pbn__entry.Is(3) ? ((MessageSegment)__pbn__entry.Object) : default(MessageSegment); }
            set { __pbn__entry = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializePrevious()
        {
            return __pbn__entry.Is(3);
        }
        public void ResetPrevious()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__entry, 3);
        }

        [global::ProtoBuf.ProtoMember(1, Name = @"segment")]
        public MessageSegment Segment
        {
            get { return __pbn__entry.Is(1) ? ((MessageSegment)__pbn__entry.Object) : default(MessageSegment); }
            set { __pbn__entry = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
        }
        public bool ShouldSerializeSegment()
        {
            return __pbn__entry.Is(1);
        }
        public void ResetSegment()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__entry, 1);
        }

        [global::ProtoBuf.ProtoMember(4, Name = @"next")]
        public ReadyForNext Next
        {
            get { return __pbn__entry.Is(4) ? ((ReadyForNext)__pbn__entry.Object) : default(ReadyForNext); }
            set { __pbn__entry = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeNext()
        {
            return __pbn__entry.Is(4);
        }
        public void ResetNext()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__entry, 4);
        }

        [global::ProtoBuf.ProtoContract()]
        public partial class ReadyForNext : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public ReadyForNext()
            {
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1, Name = @"at")]
            public long At { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MessageSegment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MessageSegment()
        {
            Uri = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"from")]
        public Timestamp From { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"until")]
        public Timestamp Until { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uri { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BackwardSegment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public BackwardSegment()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"until")]
        public Timestamp Until { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"segment")]
        public PackedSegment.Next Segment { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"snapshot")]
        public PackedSegment.StateSnapshot Snapshot { get; set; }

    }

}

#pragma warning restore 0612, 0618, 1591, 3021
#endregion
